### ISSUE TITLE
Klipper Console Output does not show newlines

### ISSUE THREAD

**Issue by oderwat** [mmone/OctoprintKlipperPlugin#20]
I am using DELTA_CALIBRATE with some macros (using my phone as 'remote control' standing before the printer). Before I ask to add it as a feature that the plugin updates the configuration automatically I would be already pretty happy if it would show the newlines in the output. I guess this applies to other commands (mesh points?) too.

![image](https://user-images.githubusercontent.com/719156/44635174-925a7d00-a9a2-11e8-8183-e71c00a8d89e.png)

The above should be more like

```
stepper_a: position_endstop: 292.737549 angle: 89.603791
stepper_b: position_endstop: 291.898510 angle: 208.752638
stepper_c: position_endstop: 292.145320 angle: 330.000000
delta_radius: 132.776768
To use these parameters, update the printer config file with the above and then issue a RESTART command
```

**Comment by oderwat** [comment]
There are for sure newlines there normally. You probably need to convert those to `<br>` for the HTML output.

**Comment by mmone** [comment]
Thanks for the hint. This is now fixed in _master_.
