### ISSUE TITLE
Navbar show klipper errors

### ISSUE THREAD

**Issue by githubmath** [mmone/OctoprintKlipperPlugin#22]
Cura add always the gcode command M205.

Klipper doesn't support this command and wrote to the terminal "Unknown command:"M205". That is currently no problem, klipper ignore this.

But OctoprintKlipperPlugin writes this "error" allway to the navbar. Thats looks not very nice.
Can you add a filter or an option to disable the message in the navbar?

I cannot disable the gcode command M205 in cura and klipper ignore it.

**Comment by oderwat** [comment]
You could also add a dummy gcode macro to klipper to "eat" that command.

**Comment by githubmath** [comment]
Ohh..that is an option.  can you tell me how it works?

**Comment by oderwat** [comment]
You could do something like this:

```
[gcode_macro m205]
gcode:
  G4
```

Not sure if G4 works .. may need `G4 P0`. Or something else which does not really do something.

**Comment by githubmath** [comment]
Hey thanks. That's it.

I add only this without something more:
```
[gcode_macro m205]
gcode:
```

And the unknown command error is gone. 👍 

Issue can close...

**Comment by oderwat** [comment]
I think you can close the issue, don't you?

**Comment by dotps1** [comment]
can you tell me what config file that goes in?

**Comment by oderwat** [comment]
@dotps1 `printer.cfg` of Klipper

**Comment by dotps1** [comment]
ah, ok, I will do that after this print is done so I can reload that file
thanks!

**Comment by aphex008** [comment]
Adding
[gcode_macro m205]
gcode:

caused an error.

[gcode_macro m205]
gcode:
  G4

Worked fine

**Comment by andresgoku** [comment]
sorry noon here 
where do you add those codes?
how can I access the gcode

**Comment by dotps1** [comment]
in your printer.cfg.  you can get to it from octoprint if you have the octoklipper plugin installed.

**Comment by elcojacobs** [comment]
Perhaps a better fix is to go to your printer settings in Cura and remove the M20x commands from the start G-code instead of configuring the printer to ignore them.

**Comment by sfjuocekr** [comment]
Or use M400 instead

**Comment by camarade35** [comment]
to disable M205 error message, just uncheck jerk control in Cura, that's all

**Comment by brucetony** [comment]
> to disable M205 error message, just uncheck jerk control in Cura, that's all

This is the way

**Comment by wdclub** [comment]
I have tried all:
[gcode_macro m205]
gcode:

[gcode_macro m205]
gcode:
G4

and..
[gcode_macro m205]
gcode:
G4 P0

Nothing works.. 
Unknown command:"M205" still persist :(

**Comment by insippo** [comment]
M205 maybe help. Not m205
