### ISSUE TITLE
OctoKlipper Plugin not responding with Octoprint 1.3.10rc1

### ISSUE THREAD

**Issue by creyc** [mmone/OctoprintKlipperPlugin#30]
Octoprint 1.3.10 release candidate 1 is out and seems to break the OctoKlipper plugin.
https://github.com/foosel/OctoPrint/releases/tag/1.3.10rc1

Cannot connect or disconnect with klipper backend, and none of the buttons are responsive.

**Comment by paeppi88** [comment]
I think this is not a problem with OctoKlipper. I disabled OctoKlipper and the Printer doesn´t connect anyway.
We should wait until 1.3.10rc2 is released.

**Comment by paeppi88** [comment]
@creyc 
Try the new 1.3.10 release candidate 2. For my Printer it works with OctoKlipper again.

@mmone 
I think you can close this issue? Thank you for the great work on this plugin.

**Comment by creyc** [comment]
@paeppi88 yes you're right, RC2 works again.
