### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by ich777** [mmone/OctoprintKlipperPlugin#4]
Hello,
is it possible to make the headline "Macros" invicible or a option to turn it off?
Also it would be nice if you can make something like the Babysteps as a preset so that you didn't need it to make it yourself (this is only a idea and maby not necessary)?
Regards, Christoph
![screenshot](https://user-images.githubusercontent.com/28066518/39445049-0b870a68-4cba-11e8-8d25-c73a41549f2c.jpg)

**Comment by mmone** [comment]
Why do you want to remove the Macro headline. To have a more compact layout?
Presets could be an interesting addition.

**Comment by ich777** [comment]
@mmone Thank you for the quick reply.
Yes, exactly.
I think a option to turn the headline on and off would be a perfect solution, if thats possible and not to much work for you.
Another question, is it also possible to move the "Disconnect" button to the top bar (clicked accidentaly a few times on it)?

Btw, this plugin is super usefull, thank you for the great work and time you spent on this plugin!

**Comment by mmone** [comment]
The new release optimized spacing somewhat. Closing.
