### ISSUE TITLE
Plugin not showing?

### ISSUE THREAD

**Issue by Grimpster** [mmone/OctoprintKlipperPlugin#5]
Hey,
After installing the plugin it's not showing on the octoprint page.

![image](https://user-images.githubusercontent.com/36238141/40640498-936ac5d8-6316-11e8-88dc-13f4a65b472a.png)
![image](https://user-images.githubusercontent.com/36238141/40640536-be5ddf14-6316-11e8-93ce-1e1da2d392d9.png)

Tried installing it a few times now and doing a full reboot without luck.

**Comment by Grimpster** [comment]
Oh never mind it took about an hour before it kicked in. It's here now closing the issue :)

**Comment by mmone** [comment]
This might have been a browser caching issue.
