### ISSUE TITLE
If a drop down GUI was made for klipper configuration it would take off like a rocket. marlin who?

### ISSUE THREAD

**Issue by Crunch69** [mmone/OctoprintKlipperPlugin#7]
If a drop down GUI was made for klipper configuration it would take off like a rocket. The user would just have to select his hotend , extruder, the probe and it would build the cfg file for you.  Also add a user guide that is simple and built in.

**Comment by mmone** [comment]
This is a duplicate of #6

**Comment by mmone** [comment]
Closing this in favor of the duplicate

**Comment by mmone** [comment]
Closing
